#query_name: pl-genomes.k21
query_name: pl-genomes.k31
query_sigs: /home/ntpierce/2021-magsearch-vt/output.download_and_sketch/pl-genomes.siglist.txt
wort_sigs: /group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs
s3_dir: outputs/wort-sra/sigs
threshold: 0.01
#ksize: 21
ksize: 31
out_dir: "output.magsearch"
